# docker-compose.yml
version: '3.7'
services:
  jenkins:
    image: jenkins-docker:latest
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    container_name: wfj-jenkins
    volumes:
      - /home/wilson/jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock